version: '2'
services:
  rsyslog:
    build: ./rsyslog
    ports:
      - "514:514/udp"
      - "514:514"
    environment:
      - AWS_BUCKET=company-logs
      - AWS_ACCESS_KEY=AKIA
      - AWS_SECRET_KEY=6CtT
  example:
    image: nginx
    links:
      - rsyslog:rsyslog
  logging:
    driver: syslog
    options:
      tag: "{{.Name}}"
      syslog-address: "tcp://rsyslog:514"

